# Site settings
title: GMGIT
email:
url: https://green-it-gmgit.github.io
description: "Official website for the Governance and Management of Green IT."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: GMGIT 4.0

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url:

# Build settings
markdown: kramdown
permalink: pretty
